name: Swift CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Swift version
        run: swift --version
      - name: Build (Swift 6)
        run: swift build -v --build-tests
      - name: Run tests
        run: swift test -v
      - name: Generate DocC archive
        run: swift package --allow-writing-to-directory /tmp/docc generate-documentation --target SpeedManagerModule --output-path /tmp/docc/SpeedManagerModule.doccarchive
